version: '3.8'

services:
    smartplant_main:
        build:
            context: .
            dockerfile: Dockerfile

        volumes:
            - ./logs/:/usr/src/app/logs/

        command: python run.py --state production
        ports:
            - "8000:8000"
